### PR TITLE
Added automated way to find all generators of group

### PR DESCRIPTION
**Pull request by martin-nohava**
# Information
Created by wraping logic from `gen.py` and using it on all elements of group specified by user.

# Usage
Usage is all ready integrated in `README.md` file.

[`findgen.py <modulo>`](#findgen) - finds all generators of group  

## <a name="findgen"></a>Find all generators
* `findgen.py <modulo>` - test all elements if they are a generator in `Z*<modulo>`

example: `findgen.py 11`

### CODE REVIEW

**Comment by Bloc3k** [comment]
And here goes some nice comment <3

**Comment by martin-nohava** [comment]
Really nice. ❤️

**Comment by Bloc3k** [comment]
and use **some** md

# hello?

**Comment by Bloc3k** [comment]
naaaaaajsssuuu

**Comment by martin-nohava** [comment]
# Bigger Hello?

**Comment by Bloc3k** [comment]
and thats it, iguess

**Pull request merged**
